### ISSUE TITLE
ISO's won't boot on Apollo-Lake devices

### ISSUE THREAD

**Issue by blocksonic** [manjaro/iso-profiles#100]
Not sure if this is the correct place to report this. But all the recent released ISO's will not boot on many if not most Apollo-Lake devices. Note: it's assumed some sort of incompatability with Grub and Apollo-Lake but I have no idea.  I have one such notebook. The most recent  ISO 17.06 also would not work.
I managed to get manjaro-xfce-17.1-pre2-stable-x86_64.iso to boot, but ONLY by using the rEFInd boot manager (Grub won't work) and applying the following startup command:
misobasedir=manjaro misolabel=MJRO171P linux=boot\vmlinuz-x86_64 initrd=boot\initramfs-x86_64.img
see this thread:
https://forum.manjaro.org/t/solved-refind-live-usb-wont-boot-w-manjaro-xfce-17-1-pre2-nor-17-06/34993

**Comment by fhdk** [comment]
As of **2018-03-25** I have been testing on a low cost Apollo Lake based laptop and booting works OOB.

Only issue is the touchpad not working but that is a general kernel problem for all laptops with this touchpad.

>SYNA3602:00 0911:5288 Touchpad: libinput error: kernel bug: clickpad advertising right button
