### ISSUE TITLE
[Manjaro Gnome 17.1.0] missing fakeroot package causes update checking failure

### ISSUE THREAD

**Issue by joshirio** [manjaro/iso-profiles#103]
The update indicator (the gnome shell extension) requires fakeroot to check for updates which is not installed by default on a fresh install .Without it no updates are shown, in fact it says that everything is up to date when it's clearly not. The update check command fails because of fakeroot missing.

Not sure if this happens only when AUR support is enabled (pamac settings). Anyway, I think this package should be included because users enabling the AUR checkbox in pamac expect it to work without additional steps.

Thanks for your great work, manjaro team.

**Comment by philmmanjaro** [comment]
@Ste74 , @Chrysostomus : ideas? Do we have to update some dependencies here?

**Comment by Ste74** [comment]
Honestly not understand what you mean.. I assume you talk about 17.1.x and not 17.0.1. Anyway is normal no update is show after install.. Before is needed to rebuild.db files.. After that updates are notified.. Whitout manual intervent only wait the notification.. Anyway we don't support aur officially and for this reason as optdeoends in update-notifier pkg is listed yogurt (or pacaur)...

**Comment by philmmanjaro** [comment]
@Ste74: the question is rather if **fakeroot** is needed to have **update-notifier** or the **extension** functional.

**Comment by joshirio** [comment]
Yes sorry I meant version 17.1.0

I downloaded the gnome iso 2-3 days ago and installed it. Since I use manjaro also on different machines I noticed that the other were showing updates while the gnome install was not so I typed the "checkupdates" command into the terminal to check where the issues was and it reported missing fakeroot package.
The issues with this is, if you don't check manually for updates, the user assumes everything is up to date.

I could try a fresh install on a virtual machine if you need more detailed information.

**Comment by philmmanjaro** [comment]
**checkupdates** is part of which package? That seems to be broken then in dependency needs ...

`pacman -Qo /usr/bin/checkupdates`

**Comment by Ste74** [comment]
Now i m out of my home so i can't check what happen but
The extension is override with this
https://github.com/manjaro/packages-community/blob/master/gnome/gnome-shell-extension-manjaro-update/10_manjaro-update.gschema.override
So the checkupdate command is the original.. Humm

**Comment by joshirio** [comment]
yes the correct command is "/usr/bin/update-check" my bad. This binary is part of the package "update-notifier"

**Comment by philmmanjaro** [comment]
@Chrysostomus: do we have a dependency for **fakeroot** to get **update-notifier** functional? I didn't found any source of it.

**Comment by philmmanjaro** [comment]
@joshirio: can you print me an error message you get when **fakeroot** is not present?

**Comment by Ste74** [comment]
@philmmanjaro : btw open this some time ago 
https://github.com/manjaro/pamac/issues/375
in this way is a pure pamac sourced

**Comment by joshirio** [comment]
> @joshirio: can you print me an error message you get when fakeroot is not present?
```
$ update-check
==> ERROR: Cannot find the fakeroot binary.
```

**Comment by Chrysostomus** [comment]
I did not know it needs fakeroot but apparently it does. I'll add the dependency.

**Comment by Ste74** [comment]
Consider closed via 
https://github.com/manjaro/packages-community/commit/5df521323f2813565a78300d25f21b3c475d3348
reopen if needed ;)
