### ISSUE TITLE
Add the Ubuntu Budgie Extras

### ISSUE THREAD

**Issue by boredland** [manjaro/iso-profiles#109]
Hi!
I've been using the Ubuntu Budgie Extras on my Manjaro Budgie for a few days now and for me they look like they make a real difference in usability for budgie. What do you think?
Yours
Jonas
https://github.com/UbuntuBudgie/budgie-extras
https://aur.archlinux.org/packages/budgie-extras-git/

**Comment by Ste74** [comment]
Hi :smile: .. i see you are the mainatiner of the AUR pkg and maintainer into the github repo .. if you warning or do PR ( after inclusion in Manjaro ) why not :wink:

**Comment by boredland** [comment]
Yeah. I've been using Budgie on Manjaro as a replacement for Gnome: The Budgie Extras seem to add  everything I missed coming from the gnome world. But you're wrong: I'm not mantainer of the github-repo.

**Comment by Ste74** [comment]
> But you're wrong: I'm not maintainer of the github-repo.

Right my error .. you are a contributor :wink:

**Comment by Ste74** [comment]
closed via https://github.com/manjaro/iso-profiles/commit/491ea57981544f0a159f91ee60ef09cbad91bdfe
