### ISSUE TITLE
Tablets and Pen displays (wacom but not only)

### ISSUE THREAD

**Issue by bogdancovaciu** [manjaro/iso-profiles#111]
As most of my work is related to drawing I was looking for solutions to get the tablet working on my DE, and keep my workflow as it is, without reaching out for scripts, keyboard shortcuts or Terminal commands.
This is what I found so far and stripped down to minimum information:
1. On Cinnamon, Gnome and Budgie, the only thing that is needed to install aside from the default installer is the package _xf86-input-wacom_.
2. On KDE Plasma, that I prefer as my main working environment, the package _xf86-input-wacom_ will be automatically installed once I install the _[kcm-wacomtablet-git](https://aur.archlinux.org/packages/kcm-wacomtablet-git/)_ from AUR. Not sure this will make people happy to have it by default installed, or have it in the Manjaro repos, but for sure for some will avoid the confusion created by the wacom packages that come up in the search whatever using pamac, pacui or octopi or even searching on internet for a solution to it.
3. On XFCE and probably MATE there is a workaround proposed by **[achadwick](https://github.com/achadwick/gsdwacom4xfce)** and works just fine.
4. On the tiling window managers this wouldn’t be beneficial IMHO, and on most of them there is no way to get a GUI like configuration settings, so people have to make use of the _xsetwacom_ commands. Aside from that, because the tiles are manipulated trough keyboard, the workflow with a tablet and pen is not so efficient.

Detailed information to other posts that also have a particularity:
https://forum.manjaro.org/t/very-slow-drag-and-drop-on-plasma-5/42099/2?u=bogdancovaciu
https://forum.manjaro.org/t/no-wacom-effort-from-the-manjaro-team/22040/23?u=bogdancovaciu

Depends also on how those that maintain the drivers if will add new ID's and layouts to the existing ones, to render out all the issues and questions regarding unsupported (yet) hardware. This might create a bit of conflict if people start reporting issues to Manjaro and not to the developer of that/those packages, and probably is better to avoid adopting them.

Thanks for your attention!
Bogdan

**Comment by Ste74** [comment]
What about write a guide in our [wiki](https://wiki.manjaro.org/index.php?title=Main_Page) ?
If you don't want request an account you can write the text and submit ( at me or other with wiki access )

**Comment by bogdancovaciu** [comment]
Most of the times if people just follow what i mentioned above, they will have the tablet working. There are particular situations when additional things i had to do, but i no longer have the _wacom bamboo fun_ and _intuos4_ tablets, and i don't recall all the details, it was 5 and 3 years ago. If someone gives me the info and the issue, most likely i can give some answers but i can't guarantee it will work., not at the first try anyway.
The wiki would be more about **what not to do**, because i have seen people tend to install countless packages that get in conflict, then mix _xsetwacom_ commands with the _GUI Settings_ and then they jump to _xbindkeys_ ... so they end up in a mix that renders all unusable ...
If is possible to add the packages i mentioned to the default install, there might be chance to ask people for testing and feedback, gather that information and see if future intervention is needed.

**Comment by bogdancovaciu** [comment]
Not sure this will serve for a wiki ...
[For_Tablets.docx](https://github.com/manjaro/iso-profiles/files/1851427/For_Tablets.docx)
Cheers!

**Comment by fhdk** [comment]
@bogdancovaciu 
Agree with @Ste74 

Added to wiki https://wiki.manjaro.org/index.php?title=Wacom_Tablet_And_Pen

**Comment by bogdancovaciu** [comment]
That means this issue can be closed? Since it was addressed and fixed, i think is ok to close it ... Let me know and THANKS a lot!!!

**Comment by fhdk** [comment]
If you think so - let me close it for you. 

And thank your!!!!
