### ISSUE TITLE
Adapta Manjaro Shell Theme

### ISSUE THREAD

**Issue by bogdancovaciu** [manjaro/iso-profiles#112]
After our discussion regarding the wacom settings not being visible while using the _manjaro-gnome-maia-theme_, and you find a solution to it, i decided to have a look at why the login screen, lock screen do not match the default Adapta theme (the buttons have a different style, the panel has a different style, the user login icon and password box has a different style), so i played a bit with the Adapta gnome-shell theme, and ended up having the same issue, the tablet settings where not visible, just a blank transparent overlay.

After looking at the *.css files it seems that the _pad-osd.css_ was the issue, and was making everything to have the same transparency and color as the rest of that settings overlay. Changed that and recompiled the _gresource_ ... Now all looks more unified in the same style of the Adapta theme, and the tablet settings buttons interface is visible too.

Here is the file that also contains the source (few icons, the fixed css and the xml) and the compiled _gnome-shell-theme.gresource_
[Adapta-Manjaro-shell-theme.zip](https://github.com/manjaro/iso-profiles/files/1863917/Adapta-Manjaro-shell-theme.zip)

The thing is, shouldn't **Tweaks** settings take care directly of the symlink ? (lets's say) I chose the theme and it applies it something like:
```
ln -sf /usr/share/themes/Adapta-Nokto-Eta-Maia/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource 
```
of course if that theme has the _gresource_ and doesn't have a *.css that renders something completely invisible.
Also this will make the `/usr/share/gnome-shell` folder more clean, remain consistent in that particular style/theme/colors ...
Let me know what you think.
Cheers!

**Comment by Ste74** [comment]
Hi, not sure understand correctly your comment.. i have see the theme into the zip file: this is the adapta icon set ? This is my source used for the [manjaro-gnome-theme](https://github.com/Ste74/manjaro-gnome-theme/tree/master/theme).. 
i have used the adwaita set and re worked with maia color .. the reason is here.. take a look
https://github.com/manjaro/manjaro-gnome-settings/issues/13

**Comment by bogdancovaciu** [comment]
No, is not the icon set, is the gnome-shell for login and lock-screen that i tweaked so it looks the same as the Adapta theme from manjaro default install. It also displays correctly the wacom settings and it doesn't crash the shell when is used. At least it didn't crash on my system. It has the minimum resources required (the SVG files) ... is even possible to create the _gnome-shell-theme.gresource_ only with the CSS files without the assets/icons ... It might have crashed previously because there are a few inconsistencies in the theme itself, but i'm no coder so ... 

I was wondering why once you  select the Shell theme in the Tweak Tool it doesn't create a symlink to the gnome-shell folder. I'm sorry i can't be more clear for my lack of technical vocabulary.

**Comment by Ste74** [comment]
Don't worry .. let me grab your modifications and push for testing since now we have started the **18.0 Illyria** development :smile:

**Comment by bogdancovaciu** [comment]
You might want to change the _noise-texture.png_ ... i did modify it when was sun outside, but now that is darker outside, it seems that the colors on it are too saturated (visually), and it bothers me a bit. I will play with something that is not so strident ... Cheers!

**Comment by Ste74** [comment]
Please note that .. i need a tiled image :wink: 
You can use this repo 
https://github.com/Ste74/manjaro-gnome-theme/tree/development

**Comment by bogdancovaciu** [comment]
The one made by Muser is nice! Is quite interesting (not really a good thing) the way GDM theme is tiling the image, but here is a squared one i tried ...
![noise-texture](https://user-images.githubusercontent.com/37552419/38156128-6ed78c6c-3484-11e8-8227-3f76d43bf132.png)

**Comment by bogdancovaciu** [comment]
Believe it or not, but i ended up by using this after all ... 
![noise-texture](https://user-images.githubusercontent.com/37552419/38156651-4a4972e4-3488-11e8-8d3a-f9954f03fac7.png)

**Comment by bogdancovaciu** [comment]
Made a few more tests and turns out that Adapta-Nokto-Eta-Breath is a bit more consistent. The only thing it has to be changed is the code inside the **pad-osd.css**, so i made it like this:
```
.Leader {
    stroke-width: .5 !important;
    stroke: #16A085;
    fill: none !important;
}

.Button {
    stroke-width: .25;
    stroke: #ededed;
    fill: #2c383e;
}

.Ring {
    stroke-width: .5 !important;
    stroke: #16A085 !important;
    fill: none !important;
}

.Label {
    stroke: none !important;
    stroke-width: .1 !important;
    font-size: .1 !important;
    fill: transparent !important;
}

.TouchStrip, .TouchRing {
    stroke-width: .1 !important;
    stroke: #ededed !important;
    fill: #2c383e !important;
}
```
The **gnome-shell-theme.gresource.xml** contains this:
```
<?xml version="1.0" encoding="UTF-8"?>
<gresources>
  <gresource prefix="/org/gnome/shell/theme">
  	<file>gdm3-Adapta-Nokto-Eta.css</file>
    <file>gnome-shell.css</file>
    <file>gnome-shell-high-contrast.css</file>
    <file>noise-texture.png</file>
    <file>pad-osd.css</file>
    <file>key-enter.svg</file>
    <file>key-enter-active.svg</file>
    <file>key-hide.svg</file>
    <file>key-layout.svg</file>
    <file>key-shift.svg</file>
    <file>key-shift-latched-uppercase.svg</file>
    <file>key-shift-uppercase.svg</file>
    <file alias="message-indicator-symbolic.svg">message-indicator-symbolic.svg</file>
    <file>no-events.svg</file>
    <file>no-notifications.svg</file>
    <file>process-working.svg</file>
    <file>toggle-off.svg</file>
    <file>toggle-on.svg</file>
  </gresource>
</gresources>
```
The reason why i don't think is necessary to add more assets, when generating the **gnome-shell-theme.gresource**, is because are handled by the **gnome-shell.css** + **gdm3-Adapta-Nokto-Eta.css**
Once i regenerated the **gnome-shell-theme.gresource**, i made a symlink of it:
```
sudo ln -sf /usr/share/themes/Adapta-Nokto-Eta-Breath/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource
```
This is the structure and folders/files i have (previously was a bit more crowded)
![image](https://user-images.githubusercontent.com/37552419/38173097-cef6cc92-35c0-11e8-8dd6-a32c5776aefb.png)

Now the entire interface looks consistent with the theme, whatever is in lock screen or the login screen + when inside the desktop: buttons, authentication popup, shutdown ...
![image](https://user-images.githubusercontent.com/37552419/38173123-51c1bc0e-35c1-11e8-8186-ef04694ba0c7.png)
And the Tablet configuration looks ok also (because of the **pad-osd.css** change), because previously was not visible, as i mentioned (your fix was and is working, but that Maia gnome-shell theme looks different). On this particular install i didn't set the buttons yet to my tablet, that is why all the entries look "none" :)
![image](https://user-images.githubusercontent.com/37552419/38173162-cd0787ae-35c1-11e8-9430-1346a8a08f6d.png)

Now the only thing to make is a decent tiling background for GDM, that will look great on whatever screen resolution. I will think to it and try some different approach to the design of it.
Hopefully this post doesn't sound pretentious, or that i force you to go with the proposal, and sorry for being so lengthy.
Cheers!

**Comment by bogdancovaciu** [comment]
How about this image for the lock/login screen ?
![image](https://user-images.githubusercontent.com/37552419/38174180-318ea30a-35d2-11e8-82f3-04abed17f207.png)

**Comment by bogdancovaciu** [comment]
Or this one
![image](https://user-images.githubusercontent.com/37552419/38174309-d298edea-35d3-11e8-9de6-9308e0e2a52b.png)

**Comment by bogdancovaciu** [comment]
Hello again!
Just received the update on _unstable_ and because the themes where also updated, and because i had a symlink from the Adapta-Nokto-Eta-Maia to the gnome-shell folder, the lock and login screen reverted  from what i had changed. Gladly i saved one of my modifications but to Adapta-Nokto-Eta-Breath ... Anyway, those two look similar ... 
Also i noticed that on both, the pad-osd.css has the same old code, and that rendered the tablet settings invisible again.

I made a test and looked once again at the css files, and i realized that is possible to make a hack in order to make this themes have a branded login screen.
If i edit the gnome-shell.css in the Adapta-Nokto-Eta-Breath, and i change this line:
`#lockDialogGroup { background: #222d32 url("noise-texture.png"); background-repeat: repeat; }`
to
`#lockDialogGroup { background: #222d32 url("branding.png"); background-center: center; }`

The branded image will be something like this and will have the name _branging.png_inside the theme, where is also the _noise-texture.png_:
![branding](https://user-images.githubusercontent.com/37552419/38177278-88165e04-3607-11e8-91d7-2698ec0ed886.png)
The _noise-texture.png_ will be used by the _gdm3-Adapta-Nokto-Eta.css_ that will remain as it is, and is seen for a brief time during the login.
Now the _gresource_ file will be generated using this _gnome-shell-theme.gresource.xml_:
```
<?xml version="1.0" encoding="UTF-8"?>
<gresources>
  <gresource prefix="/org/gnome/shell/theme">
    <file>gdm3-Adapta-Nokto-Eta.css</file>
    <file>gnome-shell.css</file>
    <file>gnome-shell-high-contrast.css</file>
    <file>noise-texture.png</file>
    <file>branding.png</file>
    <file>pad-osd.css</file>
    <file>key-enter.svg</file>
    <file>key-enter-active.svg</file>
    <file>key-hide.svg</file>
    <file>key-layout.svg</file>
    <file>key-shift.svg</file>
    <file>key-shift-latched-uppercase.svg</file>
    <file>key-shift-uppercase.svg</file>
    <file alias="message-indicator-symbolic.svg">message-indicator-symbolic.svg</file>
    <file>no-events.svg</file>
    <file>no-notifications.svg</file>
    <file>process-working.svg</file>
    <file>toggle-off.svg</file>
    <file>toggle-on.svg</file>
  </gresource>
</gresources>
```
Also, as i already mentioned, but important is to change the colors and transparency in the _pad-osd.css_
Because i don't know how to use github yet and how to clone packages, i prefer to attach here the entire theme i saved and worked for me all day. I didn't noticed any memory problems, nor hangs ... and all this was done from a VBox install ... while running Gimp and Inkscape + Firefox with quite a few tabs opened.
[Adapta-Nokto-Eta-Breath.zip](https://github.com/manjaro/iso-profiles/files/1866700/Adapta-Nokto-Eta-Breath.zip)

**Comment by bogdancovaciu** [comment]
Hello again!
Just received the update on _unstable_ and because the themes where also updated, and because i had a symlink from the Adapta-Nokto-Eta-Maia to the gnome-shell folder, the lock and login screen reverted  from what i had changed. Gladly i saved one of my modifications but to Adapta-Nokto-Eta-Breath ... Anyway, those two look similar ... 
Also i noticed that on both, the pad-osd.css has the same old code, and that rendered the tablet settings invisible again.

I made a test and looked once again at the css files, and i realized that is possible to make a hack in order to make this themes have a branded login screen.
If i edit the gnome-shell.css in the Adapta-Nokto-Eta-Breath, and i change this line:
`#lockDialogGroup { background: #222d32 url("noise-texture.png"); background-repeat: repeat; }`
to
`#lockDialogGroup { background: #222d32 url("branding.png"); background-center: center; }`

The branded image will be something like this and will have the name _branging.png_inside the theme, where is also the _noise-texture.png_:
![branding](https://user-images.githubusercontent.com/37552419/38177278-88165e04-3607-11e8-91d7-2698ec0ed886.png)
The _noise-texture.png_ will be used by the _gdm3-Adapta-Nokto-Eta.css_ that will remain as it is, and is seen for a brief time during the login.
Now the _gresource_ file will be generated using this _gnome-shell-theme.gresource.xml_:
```
<?xml version="1.0" encoding="UTF-8"?>
<gresources>
  <gresource prefix="/org/gnome/shell/theme">
    <file>gdm3-Adapta-Nokto-Eta.css</file>
    <file>gnome-shell.css</file>
    <file>gnome-shell-high-contrast.css</file>
    <file>noise-texture.png</file>
    <file>branding.png</file>
    <file>pad-osd.css</file>
    <file>key-enter.svg</file>
    <file>key-enter-active.svg</file>
    <file>key-hide.svg</file>
    <file>key-layout.svg</file>
    <file>key-shift.svg</file>
    <file>key-shift-latched-uppercase.svg</file>
    <file>key-shift-uppercase.svg</file>
    <file alias="message-indicator-symbolic.svg">message-indicator-symbolic.svg</file>
    <file>no-events.svg</file>
    <file>no-notifications.svg</file>
    <file>process-working.svg</file>
    <file>toggle-off.svg</file>
    <file>toggle-on.svg</file>
  </gresource>
</gresources>
```
Also, as i already mentioned, but important is to change the colors and transparency in the _pad-osd.css_
Because i don't know how to use github yet and how to clone packages, i prefer to attach here the entire theme i saved and worked for me all day. I didn't noticed any memory problems, nor hangs ... and all this was done from a VBox install ... while running Gimp and Inkscape + Firefox with quite a few tabs opened.
[Adapta-Nokto-Eta-Breath.zip](https://github.com/manjaro/iso-profiles/files/1866700/Adapta-Nokto-Eta-Breath.zip)

**Comment by philmmanjaro** [comment]
@Ste74: may you look into this? @bogdancovaciu: can it be that your wrote the same comment twice?

**Comment by Ste74** [comment]
Yep  sorry @bogdancovaciu in this days was a little busy with holiday.. I started tomorrow the learning :wink:

**Comment by bogdancovaciu** [comment]
It seems so, i had two browsers opened on two machines and while making some tests ... not sure if got refreshed or what happened ... I removed one comment. Thanks for taking the time to read this. 
Now i'm learning too about how the themes are made and how are working ... :)
Cheers!

**Comment by Ste74** [comment]
Hi @bogdancovaciu .. awesome work... the look of new gdm screen is wonderfull.. question: how about multiscreen ? Is ok in this situation?

**Comment by bogdancovaciu** [comment]
For multiscreen the GDM+gnome-shell is a conundrum ... My solution doesn't work. I tried also to set the background as:
```
#lockDialogGroup { background: #222d32 url("branding.png"); background-repeat: no-repeat;
    background-size: cover;
    background-position: center center;
 }
```
but on dual display acts very funky, looks bad it makes no sense ... 

My problem with this is that if the login input dialog happens on primary display only on GDM, why not the background ? More i'm reading about this, the more i have a headache, but the thing is this is the first time i look into this, and i have no experience whatsoever.
I will keep you up to date to my findings. Also i will try to see if the Adwaita clean/default does a better job. Also i'm in the process of making some new themes for the entire interface, so that way i can learn better how all this works.

**Comment by bogdancovaciu** [comment]
Hello guys,
Made a few changes in my approach and i dropped the idea of using _.png_ file for lock/login screen and also on using it as _no-repeat_, _cover_ or _center_ in the _.css_ file. It didn't work for dual screen if it worked for single screen ... all the combinations i did end up looking bad in some situations. Not to mention that those that have 4K displays will call it a joke. :)
So, my proposal is (since GDM and Gnome Shell deal nicely with _.svg_ files) to use a pattern i just did and is branded Manjaro :) I will not reveal it here because i want you to test it, so i will attach only the **gnome-shell** folder for **Adapta-Nokto-Eta-Breath** theme, not the entire theme ...
The advantage of using .svg are:
1. can be edited and altered by anyone, as long as after they done the editing, they Unify the paths that have the same color. It reduces the file size a lot.
2. even if the design is resized for the liking, the pattern remains the same and the file size remains the same
3. the colors cand be changed, using transparency or not, so it can integrate with the background from the theme, or overwrite it by using 255 in the rgba 
4. the lock screen background looks very sharp and nice, it doesn't get blurred because of the .png (depending how it was exported)
5. it will look the same on whatever display, resolution or multi monitor setup.

Here is the file:
[Adapta_Nokto_Eta_Breath_gnome-shell_ONLY.zip](https://github.com/manjaro/iso-profiles/files/1878007/Adapta_Nokto_Eta_Breath_gnome-shell_ONLY.zip)
If you like my approach i will have more designs, and i will do my best to learn how to make a complete theme too.
Cheers!

**Comment by Ste74** [comment]
@bogdancovaciu let me build this and release in community :wink: do you think? I will build a new pkg so can be installed as request for test/development purpose and we can paly with it :smile:  .. only i think is better not include in xml file the `gdm3-Adapta-Nokto-Eta.css` because i think this can break all other themes.. when do ( if ok for  you ) the pkg i build the gresource file whitout this css file ..
Do you think ?

**Comment by bogdancovaciu** [comment]
@Ste74 - I kept the `gdm3-Adapta-Nokto-Eta.css` just because was in the theme, but i did realized now that is not needed at all, so you can exclude it. I will test the installer you made on a system that i didn't tempered with, or even i will make a new Gnome install from the latest install media, so we know all is ok with this. 
Looking forward to it!!!

**Comment by bogdancovaciu** [comment]
Just made a test with your new installer, and i think we are on the right track, but the `assets` and that folder must be included when compiling with the .xml file, because the `gnome-shell.css` file is looking for them in the binary `theme.gresource` file and are not present, and because of that is falling back to some information from **Adwaita** binary. Also i think the `noise-texture.png` should be included for the same reason, just to keep the theme look, otherwise is also displaying the _noise_ from **Advaita** binary.

More explanation:
1. once i installed the GDM theme i went to Tweak Tool and chose the Shell to _Default_, so is using strictly the binary provided by the installer.
![image](https://user-images.githubusercontent.com/37552419/38459346-1c98f2fa-3ab1-11e8-870f-03bcf3aa7b8f.png)
1a. the Dash (Show Applications) has no **dots**, no icon, because those are in the _assets_ folder, but without them in binary is rendered without.
1b. the dialogs for password is using a mix of styles from Maia theme and Adwaita. If i run **_Open as Administrator_** in **Files** i get this style buttons:
![image](https://user-images.githubusercontent.com/37552419/38459195-75fe8b36-3aaf-11e8-84f6-a22b516c0b1b.png)
1c. the shutdown dialog also uses a mix of styles:
![image](https://user-images.githubusercontent.com/37552419/38459203-a014e6fe-3aaf-11e8-9b66-46e8bc95fd58.png)

2. the Panel and the Login screen look ok and follow the theme, but not the shutdown dialog

3. if now i chose the **Adapta-Nokto-Maia** Shell in the Tweak Tool will fix the above mentioned points 1a, 1b and 1c but not 2
They should look the same with or without a theme selected in the Tweak Tool
![image](https://user-images.githubusercontent.com/37552419/38459374-5c390724-3ab1-11e8-9a0e-a67cd4416880.png)
and for shutdown
![image](https://user-images.githubusercontent.com/37552419/38459378-71c208b6-3ab1-11e8-8b54-6392eecf586c.png)

Not sure what is the best approach to this. Because as you mentioned, including the gdm3-Adapra-Nokto-Eta.css too, might break the other themes, but ... maybe only for the shutdown protocol from the login screen, not when another shell theme is active from the Tweak Tool while the user is still logged in.... At least this is what i observed.

There are a couple of particularities with this:

- A. the user makes use of a different GTK theme that has no shell theme, and the popup dialog for authentication and shutdown uses the shell style, so will be a lot of mixed stuff there and they will not know what is going on.
- B. the user will chose a different GTK theme that also has a shell theme. Once is logged out or in lock screen, the shell theme will be different because is using the binary file. Once again it will create confusion and they might try to change stuff, ending up in a broken GDM (black screen, only mouse cursor, inconsistent dash application running dots, etc)
- C. after installing a GTK theme that has also a shell theme, they will replace the binary file. Most themes are outdated and do not have a complete set of assets in them, not a proper css file for shell. They don't know that the developers now make use of SASS/SCSS files for source, make there the modifications and then compile the css for the theme. By replacing the file from your installer, they will find that that package might not update properly, or ... they will remove it and in that process thei will remove actually their file. They will reboot and the shell will fall back to Adwaita one. All this will make people more confused.

All this is speculation based on few experiences i had and discussions with some folks. Somehow i understand the Gnome developers, but on the other hand is impossible for normal users to get what they want without a heavy research on forums and documentation.

While the [Oomox](https://github.com/themix-project/oomox) does a decent job, is incomplete and you still have to fix manually some stuff if you create your own theme with it. Also is using same assets, and depending if you use the Materia or Flatix/Numix engine, you end up with or without shell theme included, and a complete different look between the two.

Hope my rant didn't got way to lengthy. Thank you kindly for your patience and diligence to make all this.
Cheers and a great weekend!!!

**Comment by bogdancovaciu** [comment]
Got back to it and checked the original Adapta Maia theme and there where a few things that didn't match. The attached file contains the binary but also the source + xml to compile and some fixes i thought need to be applied. Also indeed there is no need for another css files, but the assets must be included. I also included the _workspaces-to-dock_ but might not be needed, but the assets folder do need to be there, otherwise the dialog for authentication and shutdown will look out of the theme.
[Original_modified_Adapta_Maia_gnome-shell.zip](https://github.com/manjaro/iso-profiles/files/1887243/Original_modified_Adapta_Maia_gnome-shell.zip)


Because you mentioned you will upload it to AUR, i made an Arch branded GDM for Adapta Maia too. Here is the file and the source, only changed the design of the branded.svg to arch linux. Hope people will like it.
[Arch_Adapta_Nokto_Maia_GDM_shell.zip](https://github.com/manjaro/iso-profiles/files/1887245/Arch_Adapta_Nokto_Maia_GDM_shell.zip)

Cheers!

**Comment by Ste74** [comment]
Thank you.. Now i m out.. So this night or at last tomorrow i m able to do this revision :D

**Comment by Ste74** [comment]
Close via https://github.com/manjaro/packages-community/commit/8c76317ca9e6ca812a96729e3ed8f27ae569f825
@bogdancovaciu feel free to reopen if needed :wink: Soon upload an alpha iso for gnome with this theme to see what happen :smiley:
