### ISSUE TITLE
Deepin monospaced font is broken 

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/iso-profiles#114]
Deepin edition reports the default monospaced font to be unsupported. This causes the terminal font to be garbled as characters overlap.

Suggested solution: set monospaced font to Not only Sans Mono by default. 

@oberon2007

**Comment by philmmanjaro** [comment]
Which font was used?

**Comment by Chrysostomus** [comment]
Ah, I see that autocorrect has mangled my previous post. The font was set to maybe Noto Mono. The font that worked properly was Noto Sans Mono. Seems like a case of misspelling in config or changed font name.

**Comment by philmmanjaro** [comment]
The issue is documented in our update announcements. The compat package is needed to be installed. Not an Issue of Deepin, rather a bug in the font, which is also documented.

**Comment by Chrysostomus** [comment]
Well, that sucks. Anyway, this bug is present in the installed system out of the box and I don't it should. Maybe we should add in the compat package?

**Comment by oberon2007** [comment]
I can simply have the deepin-settings pkg depend on the compat pkg.
Do I have to use a different font name in the config now, too?

**Comment by oberon2007** [comment]
To be honest I don't see any problem with the font as it is? Terminal text looks perfectly fine with the default setting and current stable packages...
How can I reproduce the problem?
Or has the issue not yet arrived on stable branch?

![screenshot_2018-04-12_20-03-44](https://user-images.githubusercontent.com/11800714/38695494-bc0ba858-3e8c-11e8-8da1-252c6fe9619a.png)

**Comment by oberon2007** [comment]
ok. I guess the issue is now only on testing branch, right?

**Comment by philmmanjaro** [comment]
Since it depends on Noto-Fonts, then yes. **testing** and **unstable**.

**Comment by oberon2007** [comment]
Adding the compat pkg to **deepin-dektop-schemas-manjaro** since this is the pkg actually depending on noto-fonts.
