### ISSUE TITLE
Minimal xfce ?

### ISSUE THREAD

**Issue by fassily** [manjaro/iso-profiles#115]
'LLo,

It sounds that with basic flag:
manjaro-xfce-gtk3-minimal-settings no longer exits (yet ?)

**Comment by oberon2007** [comment]
I'm not sure if we will really need it. The whole thing with -gtk3- named packages is only temporarily anyway.
However it shouldn't cost a big effort to package - if differences to the gtk2 version are needed at all. I'll look at it a bit later.

**Comment by oberon2007** [comment]
https://github.com/manjaro/manjaro-xfce-settings/commit/cfd452835030291322ace30b3f5f143f186fcbbb
https://github.com/manjaro/manjaro-xfce-settings/commit/69a92d1b0cb52eb12d1af45e81abdb18897ca0e0

**Comment by fassily** [comment]
'LLo,

Sorry for the very late answer, I was away!
Yep for sure, but it's just that ">basic 
manjaro-xfce-gtk3-minimal-settings" in the Package-Desktop of xfce 
profile doesn't seem to exist in the repositories ?


Le 2018-04-26 12:21, James Kittsmiller a écrit :

**Comment by oberon2007** [comment]
It does since last night on the unstable branch :wink: 
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20180430/016514.html

**Comment by oberon2007** [comment]
meanwhile it is in testing already.
