### ISSUE TITLE
Manjaro XFCE desktop setup is broken because of a replaced package

### ISSUE THREAD

**Issue by rgeorgiev583** [manjaro/iso-profiles#117]
Commit `ccb9b107382432a3af43dc21e2faabdd707e38d7` seems to break the installation process of the **full** version of the Manjaro **desktop** system with the **XFCE** desktop environment via the Manjaro Architect for me:

```
looking for conflicting packages...
warning: removing 'gtk3' from target list because it conflicts with 'gtk3-classic'
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: vibrancy-icons-teal and vibrancy-colors are in conflict
==> ERROR: Failed to install packages to new root
```

Can you please revert it (or at least workaround it)?

**Comment by Ste74** [comment]
Same problem discuss here
https://github.com/manjaro/iso-profiles/commit/ccb9b107382432a3af43dc21e2faabdd707e38d7#commitcomment-28783447

**Comment by philmmanjaro** [comment]
Fixed via https://github.com/manjaro/packages-community/commit/5db9e975b94a97c2436ae68f173f545f16c90148. @Chrysostomus: why is **Architect** point to the **Master-Branch** we do development for **v18.0**? Stable branch is named **v17.1**.
