### ISSUE TITLE
[kde] apps

### ISSUE THREAD

**Issue by udeved** [manjaro/iso-profiles#12]
Should we replace pure qt apps with kde base apps?
16.12 has these kf5 ported.

qpdfview -> okular
qupzilla -> konqueror

etc

**Comment by Kirek** [comment]
Yes for okular (done with kde-minimal), but konqueror it's on life support, I prefer to keep qupzilla.

**Comment by udeved** [comment]
I have added an extra=true/false to profile.conf to activate extra packages.
 ie use minimal profile and pull extra packages, drop full profile and rename it to kde.
