### ISSUE TITLE
webdad-profile up-to-date?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/iso-profiles#121]
With current situation **manjaro-architect** will offer all profiles present on the `iso-profiles::manjaro-architect` branch for installation.
I see that **webdad** has not seen any commits in a while. So my question is, is the profile in a state were it makes sense to install it with **m-a** or can we update it? Or should be - at least temporarily - remove it on the architect branch?
@codesardine

**Comment by codesardine** [comment]
I am about to update it soon, It can always be removed, and re add it after.

I don't know what an m-a is?

**Comment by oberon2007** [comment]
**m-a** is short for **manjaro-architect** :wink:

**Comment by oberon2007** [comment]
yep. guess do! :wink:
