### ISSUE TITLE
i3 profile seesm to be missing openrc packages

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/iso-profiles#16]
openrc version of i3 edition does not seem to have whatever package provides xdm service. @oberon2007

**Comment by oberon2007** [comment]
Since it uses **lightdm**, why would an xdm.service be needed?

**Comment by Chrysostomus** [comment]
It is my understanding that lightdm is enabled in openrc like this:
Set 

        DISPLAYMANAGER=lightdm 
In /etc/conf.d/xdm
And enable xdm with 

        rc-update add xdm default

Source: https://wiki.gentoo.org/wiki/Display_manager#OpenRC

But when manjaro-architect tries to do these steps with i3 profile on openrc base, it fails because xdm is not found.

**Comment by Chrysostomus** [comment]
I falsely remembered i3 profile having some >openrc tags and assumed that it worked with openrc. I think I may have been wrong

**Comment by oberon2007** [comment]
No, yes, it used to. I haven't supplied openrc ISOs for a while. We should update it now that the architect offers such an easy choice, though... ;-)

**Comment by Chrysostomus** [comment]
I was thinking of supplying openrc flags for bspwm too. Just need to decide what to use for acpi events instead of logind.

**Comment by oberon2007** [comment]
I'm adjusting the i3 profile right now. There is a package [**displaymanager-openrc**](https://github.com/manjaro/packages-openrc/blob/master/openrc-desktop/PKGBUILD#L135) btw! ;)

**Comment by oberon2007** [comment]
Just installed an i3-openrc with **manjaro-architect** - works fine now :smiley:
