### ISSUE TITLE
HandleLidSwitch=ignore?

### ISSUE THREAD

**Issue by boredland** [manjaro/iso-profiles#18]
At least in 16.10 and with GNOME this disables suspend on lid-closed for me. Why did you configure that?
https://github.com/manjaro/iso-profiles/blob/master/manjaro/gnome/desktop-overlay/etc/systemd/logind.conf#L24

**Comment by Ste74** [comment]
Sorry for delay , i have search the guilty but not find the right commit .. Can you try if this
https://github.com/manjaro/manjaro-tools-iso-profiles/pull/170/commits/53b9c84f3e8da14e85758b9d2edae3067e9e8814 
work in your end ? The issue mentioned there was cancelled and i can't find :( .
[There](https://github.com/manjaro/iso-profiles/blob/master/manjaro/gnome/desktop-overlay/etc/systemd/logind.conf#L24) is my actual config ( on my pc but not try your )

**Comment by boredland** [comment]
I tried some screnarios on my t440s:
1. HandleLidSwitch=ignore + Setting suspend on lid-close in ubuntu tweak - suspend on lid-close doesnt work
2. uncommenting HandleLidSwitch + Setting suspend on lid-close in ubuntu tweak - suspend on lid-close doesnt work
3. setting HandleSuspendKey=suspend - suspend on lid-close does work

**Comment by Kirek** [comment]
I think this was done because of some problems with xfce+logind a long time ago. I thought it was already removed as xfce already solved it. Dunno why it made to the gnome edition.
@Ste74 you should just remove logind.conf if you don't modify it, systemd already provides that file.

**Comment by Kirek** [comment]
@Ste74 Just checked and its manjaro-tools that set this up, so you are doing it correctly adding logind.conf to override that...

**Comment by philmmanjaro** [comment]
@Kirek: so what needs to be changed?

**Comment by Kirek** [comment]
I'm checking manjaro-tools, it seems it only changes logind.conf in the live session.

**Comment by boredland** [comment]
But the expected behaviour, at least for gnome, would be, that we could set this in the tweak-tool, right? I dont have a working configuration that achieves that, yet.

**Comment by Ste74** [comment]
Yesterday i found a more issue reported on launchpad for ubuntu gnome edition and more people set the HundleSuspendKey=suspend to solve only a minor people don't solve with this so i can do this override but seem an upstream issue with gnome/gdm ... damn

**Comment by Kirek** [comment]
I suppose HandleLidSwitch overrides tweak-tool

**Comment by Kirek** [comment]
HandleSuspendKey=suspend is the logind default...

**Comment by Ste74** [comment]
@Kirek this is the same to comment all entry in logind.conf right ?

**Comment by Kirek** [comment]
Yes, manjaro-tools only configures logind.conf for the live session, you should remove logind.conf for the budgie and gnome profiles, so it will have the default file (it has all settings commented as well).

**Comment by Ste74** [comment]
This the report on launchpad not solved at now
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1574120

**Comment by Kirek** [comment]
It seems for some laptops you need to setup HandleLidSwitchDocked=suspend for suspending to work, but that's the laptop fault reporting they are docked when in fact they are not, changing the default and "break" everything else is not the way to go...

**Comment by Kirek** [comment]
Also settings HandleSuspendKey=suspend is exactly the same as leaving the systemd default...

**Comment by Ste74** [comment]
Yes , this is how i have ask to @boredland ,[ this ](https://github.com/manjaro/manjaro-tools-iso-profiles/pull/170/commits/53b9c84f3e8da14e85758b9d2edae3067e9e8814) [here](https://github.com/manjaro/iso-profiles/issues/18#issuecomment-284032524) . Commit set logind.conf how the default ..

**Comment by Kirek** [comment]
That's why I'm telling to remove this file, so systemd default one will be there, and you don't have to care when this file updates (your current file is outdated compared to upstream).

**Comment by Ste74** [comment]
Ok , remove the override 😉 ( at the moment not at my pc , this afternoon 😄 )

**Comment by Ste74** [comment]
closed via https://github.com/manjaro/iso-profiles/commit/a9c38ff53feb91bd439fb3730ca790df16233ba1
