### ISSUE TITLE
Gnome: Replace Thunderbird by Evolution

### ISSUE THREAD

**Issue by boredland** [manjaro/iso-profiles#20]
I think Evolution provides better support for Gnome Online Accounts (sync Mail, Calendar, Tasks with Google) and a more native Gnome-Design. What do you think?

**Comment by Ste74** [comment]
I know that but is the infinite diatribe : you like Evolution , another like Thunderbird and another like Slyngshpeed etc .. Thunderbird is ( i think ) the most professional email client at the moment . I can enable/add selection for Evolution in the netgroup pkgs so user can be choice what prefer .

**Comment by boredland** [comment]
I'd like that and understand that people still like Thunderbird. My argument would only be the nice integration into the Gnome-Online-Accounts, that Gnome afaik still doesn't provide for Thunderbird.
http://askubuntu.com/questions/863462/gnome-controll-center-online-accounts-and-thunderbird

**Comment by Ste74** [comment]
Closed via
https://github.com/manjaro/iso-profiles/commit/69eb883306a959b20c37a2fece09de7b6e28ba2b
