### ISSUE TITLE
mhwd and libglvnd are in conflict

### ISSUE THREAD

**Issue by giocap73** [manjaro/iso-profiles#30]
buildiso -p budgie -b unstable
resolving dependencies...
looking for conflicting packages...
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: mhwd and libglvnd are in conflict
==> ERROR: Failed to install packages to new root
==> ERROR: Failed to install all packages
workaround  use this command:
buildiso -p  (distro)   use only stable version

**Comment by Ste74** [comment]
Already solved
