### ISSUE TITLE
Request: set KillUserProcesses=yes by default

### ISSUE THREAD

**Issue by Kzer-Za** [manjaro/iso-profiles#33]
There are some issues because by default KillUserProcesses is set to no in /etc/systemd/logind.conf. For example: https://bbs.archlinux.org/viewtopic.php?id=203080. I've also run into some trouble because of it: https://forum.xfce.org/viewtopic.php?id=11490.

In systemd upstream they have not decided yet whether or not turn it on by default, but for now, I would like to ask that it be turned on by default at least in Manjaro. As far as I understand, Manjaro positions itself as a user-friendly distro, and the behavour that results from KillUserProcesses=no is very confusing for, as someone put it in systemd discussion, naive user. Here's a comment that imho sums it up very well: https://github.com/systemd/systemd/pull/3005#issuecomment-210517466

Of course, they mention that some need it to use screen/tmux. I believe that admins that do need these tools are able to take care of themselves: they already know ins and outs of the system and settings that are not evident for a "naive user", so it would not take them much time to change /etc/systemd/logind.conf to their liking. The new user, on the other hand, will be baffled by unexpected behavior of the system. I know my way in Linux better than most newcomers, and still it took me a while to figure out what was wrong. So I would like to ask you to consider to set "KillUserProcesses=yes" by default in Manjaro.

**Comment by philmmanjaro** [comment]
Obsolete? If not please create a [new issue](https://bugs.manjaro.org).
