### ISSUE TITLE
Xfce `manjaro-printer` is not included

### ISSUE THREAD

**Issue by ThanosApostolou** [manjaro/iso-profiles#39]
@philmmanjaro I've seen that you have included a lot of printing software in the xfce's `Packages-Desktop`, however `manjaro-printer` which has `system-config-printer` as a dependency isn't included. In case you haven't seeing it, I am creating an LXDE edition which I hope that it will be accepted as a community edition at some point (https://forum.manjaro.org/t/new-manjaro-lxde-community-edition-last-updated-2017-04-02/20809?u=thanos_apostolou) and since I have kept my `Packages-Desktop` as close as possible to the xfce's one, I was wondering if you just forgot to add `manjaro-printer` or if you have a good reason that you didn't include it.

**Comment by benburrill** [comment]
Why is this closed?  XFCE and KDE still don't use manjaro-printer.
