### ISSUE TITLE
remove cronie from systemd versions?

### ISSUE THREAD

**Issue by excalibur1234** [manjaro/iso-profiles#4]
how about removing cronie from iso-profiles/shared/Packages-Root file?
full-featured versions can still add it, but it is not needed in the net-minimal version for sure.

the arch wiki uses exclusively systemd/timers now and cron has become old-fashioned there: https://wiki.archlinux.org/index.php/Systemd/Timers

here is a forum discussion about it: https://forum.manjaro.org/t/why-is-cronie-preinstalled/11470

**Comment by udeved** [comment]
If systemd world want to have basically only a systremd blob, and possibly not even a kernel in the future, just all systemd, so be it.
I don't care, Phil or Kirek need to say if they need or use "old fashioned" cron. It must be true, systemd said so its "old fashioned".

**Comment by philmmanjaro** [comment]
Hmm, seems the last **systemd** update in September blacked a lot of our community members out. Funny to read that **Gnome** was one of those DEs which had the biggest issues when the **X-Session** was gone. Anyway, I've to read up first on how and why **cronie** should be removed. It is really at last point of the development cycle and I most likely won't change it for **Manjaro 16.10**. We might discuss it for our next release, though.

**Comment by Kirek** [comment]
Since cronie is part of archlinux core we shouldn't remove it. It will also only save 275.5 kB of disk space...

**Comment by cubanpit** [comment]
I opened the forum topic because I had read on the [ArchWiki](https://wiki.archlinux.org/index.php/Cron#Installation) that `cronie` isn't installed by default; so I asked why Manjaro does install it, it seems useless for a default installation.
Maybe it's not useless now, but on my old install there were no cron job out of the box.

**Comment by philmmanjaro** [comment]
@Kirek: **cronie** isn't part of the **base** group anymore. Seems Arch dropped it now in favour of systemd timers ...

**Comment by Kirek** [comment]
Then we can get rid of it whenever we want.

**Comment by udeved** [comment]
> Hmm, seems the last systemd update in September blacked a lot of our community members out. Funny to read that Gnome was one of those DEs which had the biggest issues when the X-Session was gone. 

I still haven't gotten behind why arch remove xorg support from dbus.
It seems to create some problems for people who start gui app as root/sudo.
No dbus session launched by default for root.
Do we miss something? I mean, openrc uses dbus-x11, so it doesn't really mater, but I saw lots of froum posts on that.

**Comment by philmmanjaro** [comment]
Real old. Closing it. If still needed please open a [new issue](https://bugs.manjaro.org).
