### ISSUE TITLE
Try building an 3.24 gnome iso : gnome-shell hangs ( not appear ) 

### ISSUE THREAD

**Issue by Ste74** [manjaro/iso-profiles#45]
I'm not sure if this is the problem but after thursday i don't able to start the gnome-shell .. i.e. xorg not start , no able to start the interface ( tried to build an iso with gnome-next 3.24 but also the current is affected ) ...

**Comment by oberon2007** [comment]
Grub was already updated on March 27!

**Comment by Ste74** [comment]
I mean the [live](https://github.com/manjaro/packages-extra/tree/master/grub-theme-live) version ..

**Comment by oberon2007** [comment]
Ah! 😶

**Comment by Ste74** [comment]
My error 😉 not specified 😄

**Comment by Ste74** [comment]
Well seem related on this [bug](https://bugs.archlinux.org/task/53512)...

**Comment by oberon2007** [comment]
> Closed by  Jan de Groot (JGC)
Friday, 31 March 2017, 23:10 GMT
Reason for closing:  Not a bug
Additional comments about closing:  gnome-unstable is staging area for gnome at the moment. Don't use it until we say it's done.

😝

**Comment by Ste74** [comment]
Yeah only i see now after 3 day of test 😄 😅

**Comment by Ste74** [comment]
Yeah also fedora report this 😠 
https://bugzilla.redhat.com/show_bug.cgi?id=1435010

**Comment by philmmanjaro** [comment]
Please check what changed with **gdm-3.24.0-2.fc26**. Maybe you switch over to **lightdm** for now.

**Comment by Ste74** [comment]
Already try but is the same error . At this point is only this [bug](https://bugs.archlinux.org/task/53512) for mutter and i see in the new commit i think is solved .. i like to build the gnome group temporary but i not know the list order .. @philmmanjaro you already know the build order ?

**Comment by Ste74** [comment]
I have lost this .. gnome-next is already out and from yesterday in testing arch-repo 👍
