### ISSUE TITLE
Gnome-Suggestion: Flatplat-Theme and Paper-Icons

### ISSUE THREAD

**Issue by boredland** [manjaro/iso-profiles#48]
I am using Flat-Plat-dark as Shell and GTK+ Theme and the Paper-Icons and I'm relatively sure that this comes to an even more "complete" look&feel compared to the default Arch-Maia-Dark-Theme. What do you think?

**Comment by Ste74** [comment]
Thank you for your suggestion 😉 , i have already override the adapta gtk theme .. do you think about adapta ? have you tried adapta-maia-theme ?

**Comment by boredland** [comment]
Not really looked into it, but from what I can find in your thread the seem to look quite similar. Has it a theme for GDM, too?

**Comment by Ste74** [comment]
No not implement this now but is in my plain to implement a modified theme for gdm only i have a doubt :p .. if the GDM theme modified work without reinstall for any GDM or Shell update .. this point need a test

**Comment by codesardine** [comment]
I might work on this in the future I realy like the pink and green combination, If I do will you take the pull request in community packages, Is this something you would want in the repos? @Ste74

**Comment by Ste74** [comment]
Why not .. we can do the regular and the manjaro version ( with our coulors )  since in the repo is present this ;)
https://github.com/nana-4/Flat-Plat/blob/master/change_color.sh

**Comment by codesardine** [comment]
Sounds good :+1:

**Comment by philmmanjaro** [comment]
I'll close this one again. If still needed please open a [new issue](https://bugs.manjaro.org).
