### ISSUE TITLE
Put ceratin .desktop files here ( skel folder ) for Gnome

### ISSUE THREAD

**Issue by Ste74** [manjaro/iso-profiles#55]
Hi guys , i have a little problem in gnome settings .. @udeved can i add the .desktop file of manjaro-hello here ?  I have this conflict because i want start manjaro-hello at the start of gnome and when hello is closed i want open gnome-welcome . for do this i have created this https://github.com/manjaro/manjaro-gnome-settings/commit/66cff485d945f3474f6e17bb22c4cd5d1fc8cea8 
but now i have this because hello install already a .desktop files.. Note my .desktop files are modified to not autostart , the script call the programs .. 
/mnt/etc/skel/.config/autostart/manjaro-hello.desktop exists in both 'manjaro-gnome-settings-dev' and 'manjaro-hello'

So at the end i can override here ?

**Comment by Chrysostomus** [comment]
I think that overriding package configuration files is what the overlay is for.

**Comment by philmmanjaro** [comment]
If it is only for the live-session we might use the **live-overlay** for it. When you update the package, the original file will be restored. So, is it only for the **live-session** or also for the target installation?

**Comment by Chrysostomus** [comment]
I think that overriding package configuration files is what the overlay is for.

**Comment by Ste74** [comment]
Well , i have removed the override in gnome-settings pkg and rebuild it . In the iso pkgs list i have removed the gnome welcome but installed the gnome gettin started . The only functions interesting in gnome-welcome are the privacy and online account settings , the other are already do by manjaro settings ... The getting started pkg for gnome introduce user with video in gnome and how to use .. we will see ...

**Comment by Ste74** [comment]
Closed via 
https://github.com/manjaro/iso-profiles/commit/7f5526276e03040e088d58101cc045cbc42ae0e4
https://github.com/manjaro/iso-profiles/commit/a4a814f87dd687cbfcec1150159abaa07ffef339
https://github.com/manjaro/iso-profiles/commit/a8258c052d31898eb4c4f0d4bed4ab3d1dcdc5a1
https://github.com/manjaro/manjaro-gnome-settings/commit/2631138163cad7072b19f2cefbe3dc47c8b66965
