### ISSUE TITLE
Manjaro-aur-support meta package

### ISSUE THREAD

**Issue by Ste74** [manjaro/iso-profiles#59]
Hi , guys in order to answer at [this](https://forum.manjaro.org/t/aur-support-by-default-good-or-bad/23548) and at [this](https://forum.manjaro.org/t/a-way-to-become-aware-of-aur/23855)  i have build the [manjaro-aur-support](https://github.com/manjaro/packages-community/tree/master/manjaro-aur-support) to help users know about AUR and yaourt via our wiki via browser .
Do you think to remove all base-devel group and yaourt  from our Isos and use this metapkg ? 
@udeved , @oberon2007 , @philmmanjaro , @Kirek ??

**Comment by Ste74** [comment]
Well another question is : this metapkg install all necessary files for aur access but .. if this is installed after this inform user with a pop-up and open the browser in our wiki page for aur but ... if this is pre installed this not inform users .. so what is the approach ? We can active a .desktop after install ?

**Comment by udeved** [comment]
I haven't had time to test your meta pkg.

My idea, just rough idea would be.

Use the metapkg, but add alpm hook that checks if base-devel group and yaourt is installed.
If it is not installed, I will print a message with a hyperlink to visit wiki and tell the user how to install base-devel, eg the pacman command.
So I would start with informative messages, automation we can eventually think later how to implement?

I think you won't get this done with a *.desktop file and without user interaction, because it required root access.

**Comment by Ste74** [comment]
I think now understand .. how modify for work with alpm-hook ...

**Comment by udeved** [comment]
Reason I would favor hook, its run not between package installs, but after all transaction, at the end of process.

Have a look in /usr/share/libalpm/hooks folder, there are many examples. ;)

https://www.archlinux.org/pacman/alpm-hooks.5.html

**Comment by Ste74** [comment]
Yep another example :p [here](https://github.com/alexchernokun/pacmanity/tree/master/src)

**Comment by udeved** [comment]
More examples... 
https://github.com/manjaro/packages-openrc/tree/master/openrc
https://github.com/manjaro/packages-openrc/tree/master/eudev

**Comment by Ste74** [comment]
Add hook support .. now if yaourt is installed or found in the system a zenity notify inform user to open the manjaro aur wiki page 
https://github.com/manjaro/packages-community/commit/7463bc544980061b08df9a70955275bd0ef29875
i assume this : this hook is running any time a pkg is installed and then the script check if yaourt is present ; is this the way how work the `operation` in the trigger ?

**Comment by Ste74** [comment]
@udeved https://github.com/manjaro/packages-community/commit/0af7f82a158b151f27ec0252ebcfa298532d3b61 now i understand the hook philosophy : now this is 'armed' if yaourt is installed and open a browser in our wiki page . No depends but add in the group-devels . I push now in boxit . Now we can again improve this ? Is this what about you talking ?

**Comment by udeved** [comment]
> now this is 'armed' if yaourt is installed 
hehe, don't forget to take cover before it blows up. 💣 


Yes, you made it. Very good Ste 👍 
How does it behave in pamac or octopi with calling zenity?

**Comment by Ste74** [comment]
> hehe, don't forget to take cover before it blows up. 💣
😜 
> How does it behave in pamac or octopi with calling zenity?
Funny .. i have tested only in tty but not via pamac or octopi .. now try it and not work ( pkexec pfff ) so suspect not work also in octopi .. let me create a simply tty message 😄 and remove the groups array https://github.com/manjaro/packages-community/commit/0af7f82a158b151f27ec0252ebcfa298532d3b61#commitcomment-22268018

**Comment by Ste74** [comment]
![schermata del 2017-05-24 22-43-22](https://cloud.githubusercontent.com/assets/11218234/26424758/9e7819b0-40d2-11e7-9da8-6a4141f664ca.png)

Grr via pamac no find the browser ? 
Is also set in xdg-mime
```
~ >>> xdg-mime query default x-scheme-handler/http                                                   [1]
firefox.desktop
~ >>> xdg-mime query default x-scheme-handler/https                                                     
firefox.desktop
```

**Comment by Ste74** [comment]
![schermata del 2017-06-04 19-33-45](https://cloud.githubusercontent.com/assets/11218234/26763922/e395300e-495c-11e7-963c-681f5e4d2a7e.png)

![schermata del 2017-06-04 19-34-13](https://cloud.githubusercontent.com/assets/11218234/26763924/e5bd1ac2-495c-11e7-9aba-6cccc6115354.png)

Well guys i have modified again this interface , now you see the actual aspect : i use yad and not zenity ( yad is more powerfull than zenity ) now the windows are always on top and i use the maia svg icon and warning png icon ... Do you think ? I know is a nanny app but is designed for a totally newbie of manjaro/arch philosophy .. @philmmanjaro i don't know if you have see in action today in gnome but this is it ..

**Comment by philmmanjaro** [comment]
Ok, it is fine with me. However it didn't made it to **v17.0.2-pre6**. However I was able to ditch **yaourt** now. Please check again with @Chrysostomus in regard of **update-notifier** and if **PKGBUILD** changes are still needed for that package in regard of **(opt-)/depends**.

**Comment by Ste74** [comment]
If all work fine it not work in the prex because yaourt is in >extra tag .. this start only if yaourt or pacaur is installed 😉
