### ISSUE TITLE
Removed option for set the compression ratio ?

### ISSUE THREAD

**Issue by Ste74** [manjaro/iso-profiles#6]
Hi @udeved i not see this option .. Why ? Is usefull to build quckly 😄 , can you reintroduce with a switch key -y or what you want or maybe reintroduce in manjaro-tools.conf ?

**Comment by Ste74** [comment]
I have also this notice , checksums is removed in mt 0.14 ? I start upload for gnome edition and i have created via terminal .. Now we use only the dev signature ?

**Comment by udeved** [comment]
Checksums are generated for the sfs image inside the iso file.
You can check the md5sum at iso boot, add "checksum" to iso kernel boot option at boot prompt.
Checksums for iso file itself is generated by SF anyway.

signing will work similarly, but not implemented yet.

**Comment by Ste74** [comment]
> Checksums are generated for the sfs image inside the iso file.
You can check the md5sum at iso boot, add "checksum" to iso kernel boot option at boot prompt.
Checksums for iso file itself is generated by SF anyway.

signing will work similarly, but not implemented yet.
Yep this has sense
> As for compression ratio, I could probably later add a switch to use lowest compression for test builds, but my goal is to simplify switches and remove all unnecessary stuff unused for production purposes.
Yes , is a bit confortable when build a local iso for test in lz4 ratio ( fast compression ) btw only lz4 and xz can be used but if for other is ok no problem for me to remove the option 😉
