### ISSUE TITLE
Cannot build x64 ISO on unstable branch

### ISSUE THREAD

**Issue by ThanosApostolou** [manjaro/iso-profiles#65]
I'm trying to build an lxde ISO on unstable branch (I tried with the xfce profile too) but I get this error:
```
looking for conflicting packages...
warning: removing 'gcc' from target list because it conflicts with 'gcc-multilib'
:: gcc-libs and gcc-libs-multilib are in conflict. Remove gcc-libs-multilib? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: gcc-libs and gcc-libs-multilib are in conflict
==> ERROR: Failed to install packages to new root
==> ERROR: Failed to install all packages
==> ERROR: A failure occurred in make_image_desktop().
    Aborting...
```
However, i386 ISOs build fine. ISOs were building fine 2 days ago, before the latest gcc updates. So, maybe Packages-Desktop files need some change? Shouldn't **>multilib gcc-multilib** line override the **>gcc** one? Can anyone else build 64bits ISOs successfully?

**Comment by ThanosApostolou** [comment]
Temporary workaround is to remove line **>gcc** from Packages-Desktop when building x64 images and add it when building i686 images.

**Comment by philmmanjaro** [comment]
The issue is with **gcc-libs-multilib** and not with **gcc-multilib** itself.

**Comment by ThanosApostolou** [comment]
I close this, since it's fixed with the above commit. If something is still pending, then reopen it.
