### ISSUE TITLE
include wget by default ?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/iso-profiles#66]
As [requested](https://forum.manjaro.org/t/why-vi-is-not-preinstalled/23349/18) on the forum.
Although **wget** seems to be a commonly used utility, none of the profiles currently includes it.
Opinions?

**Comment by ThanosApostolou** [comment]
I was thinking about that 2 days ago. I tried to execute wget on my lxde ISO and I saw that it wasn't installed. Then I thought that I forgot to include it, but I found out that no other profile is using it. I totally agree with including it.

**Comment by Ste74** [comment]
Uhm i use uget in gnome and in budgie , not remember if use in mate ( i'm on smartphone now) .. wget is a cli app right? Uget the graphical front end or not ?

**Comment by oberon2007** [comment]
**uget** uses **curl** :)

**Comment by philmmanjaro** [comment]
We can add it. It depends if we should add it to all editions or let the maintainer decide ...
