### ISSUE TITLE
Suggestion to add some gnome apps

### ISSUE THREAD

**Issue by prescott66** [manjaro/iso-profiles#70]
Hi.
I want to suggest some Gnome apps, into the Gnome edition of Manjaro. I think this apps are more or less, essential apps.

gnome-calendar
bijiben
gnome-characters
gnome-clocks
gnome-weather
gnome-maps
gnome-todo
seahorse

..i think these are usefull apps, that makes gnome experience much better out of the box.

**Comment by Ste74** [comment]
Thank you for suggestion https://github.com/manjaro/iso-profiles/commit/8fd4e647e233a57cda0b908174ff831f51320d3a
add for full iso profile
