### ISSUE TITLE
MATE: problem with entering wifi password

### ISSUE THREAD

**Issue by prescott66** [manjaro/iso-profiles#71]
There is problem in MATE edition of Manjaro, when you try to connect to wifi secured with password.
Password entering dialog, is not displayed.

Fix: there is needed to add package "gnome-keyring" into live iso

**Comment by Ste74** [comment]
Already in the pkgs list : https://github.com/manjaro/iso-profiles/blob/master/community/mate/Packages-Desktop#L34
new release fix the issue 😉
