### ISSUE TITLE
Replace pa-applet with xfce4-pulseaudio-plugin in xfce

### ISSUE THREAD

**Issue by tmewett** [manjaro/iso-profiles#73]
The latter seems better in every way; it shows all active devices, including input, it actually has a mute toggle, it has a button to open the mixer (pavucontrol), and doesn't have obscure & confusing Pulse device options on right click. It's a small change that I think would please most users.

**Comment by Chrysostomus** [comment]
Seems like a user friendly choice. Which one consumes more ram?

**Comment by tmewett** [comment]
Both use negligible amounts, but for science: pa-applet uses 4 MB less, at 32 MB on my system.

**Comment by philmmanjaro** [comment]
Done with bd532105c7c80542a07a1506d1a38c183e21f021, however we have to adopt some in settings also.
