### ISSUE TITLE
Some profiles are outdated

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/iso-profiles#8]
At least i3 and deepin profiles lack lightdm and greeter from their package lists.  @oberon2007 

Many profiles include xf86-input drivers that were dropped from unstable branch with unstable update
- xf86-input-joystick
- xf86-input-acecad

Is it okay if I adjust the package lists and send a pr?

**Comment by oberon2007** [comment]
Ok about **xf86-input-joystick** and **xf86-input-acecad**, remove them.
Both i3 and deepin pull in lightdm as a dependency. (i3 has **lightdm-gtk-greeter-settings**), deepin uses a native greeter and lightdm is a dependency of **deepin-session-ui-manjaro**.

**Comment by Chrysostomus** [comment]
Aah, my mistake. I installed deepin profile and everything worked except for the lightdm. I assumed it was missing a greeter, but maybe the issue was with Plymouth.

**Comment by oberon2007** [comment]
You need to adjust **lightdm.conf** in order to use deepin-greeter. **manjaro-live** should do that automatically.

**Comment by Chrysostomus** [comment]
Thanks, that should help in scripting it...
Lxqt profile seems not to have any input drivers at all. Should I add them?

**Comment by oberon2007** [comment]
https://github.com/manjaro/manjaro-tools-livecd/blob/master/lib/util-live.sh#L123

**Comment by oberon2007** [comment]
I think new profiles should only be added here when they are ready and functional and working/tested with **mt 0.14** ...

**Comment by Chrysostomus** [comment]
I mean the lxqt profile already in this repo.

Also, should I update also sonar profiles to not to have old input drivers?

**Comment by oberon2007** [comment]
Sure, sorry! I don't really know how the current lxqt profile works. In any case the drivers were removed [on purpose](https://github.com/manjaro/iso-profiles/commit/bc5974994c3ee950339d99b0aa287f23f5085102)
The ones conflict with xorg 1.19 we need to removed from all profiles of course.

**Comment by Chrysostomus** [comment]
Okay, I'll update the pull request in the evening. 

For my purposes (using the profiles for experimental cli-installer) it would be simpler if the drivers were included, but that is not what this repo is for, so I'll adjust and let the lxqt profile be.

**Comment by Chrysostomus** [comment]
Done.
