### ISSUE TITLE
Gnome ISO: extra/firefsteam-manjaro doesn't exist

### ISSUE THREAD

**Issue by japm48** [manjaro/iso-profiles#81]
In manjaro/gnome/Packages-Desktop, there is this line preventing the ISO build: `>extra firefsteam-manjaro`.
Git blame points to 537f1b99c15d31b00cf54a727f55acf07bd5a822

So, this is probably is a typo.

**Comment by oberon2007** [comment]
Apparently a typo, yes. Thanks!

**Comment by Ste74** [comment]
Thank you @oberon2007 , @japm48 sorry for the trouble :\

**Comment by japm48** [comment]
No problem :)

**Comment by Chrysostomus** [comment]
In the future we should update iso-profiles package for all branches in case of issues like this. Installing full gnome gnome profile with manjaro-architect is still failing for some users, even after 2 weeks.

**Comment by Ste74** [comment]
You mean the release a packages in our repo ? I.e. manjaro-iso-profiles.pkg.tar.xz?

**Comment by Chrysostomus** [comment]
Yes

**Comment by Chrysostomus** [comment]
I'm wondering if manjaro-architect should just use git repo directly. When using manjaro repo package, profiles in stable branch can be nonfunctional for weeks, like happened now.

**Comment by Chrysostomus** [comment]
On the other hand, this makes manjaro-architect more vulnerable to syntax changes in this repo. But since artoo has gone to another project, I expect that the development of manjaro-tools will slow down now.

**Comment by leee** [comment]
Cool - thank you!

I can confirm I hit the same GRUB error on 0.8.18.

**Comment by Ste74** [comment]
Oh .. i see now is not rebuild the manjaro-iso-profiles after this change.. :\ .. if m-a also take the profiles into the pkg.tar.xz we have to rebuild any time ...

**Comment by Chrysostomus** [comment]
Yes, it uses the repo package by default. I'm thinking if we should use git repo directly.

**Comment by Ste74** [comment]
The problem is when the github repo  is in hard development ( if the changes are important ) .. we here talking only about a wrong list of pkgs ... No idea what is the future of M-T :\

**Comment by ThanosApostolou** [comment]
@Chrysostomus In my opinion, if manjaro-architect uses the git repo directly then it needs additional attention. Because If, for example, Stefano decides to add **>extra vala-panel-appmenu-mate** in **mate/Packages-Desktop** then this package doesn't exist in stable branch yet and it will give an error.

Maybe a solution is to add an extra branch named **stable** which will be used by manjaro-architect and move the changes there only when it's "safe"? Ofcourse, this would still needed someone to push the changes to this git branch, but it wouldn't require the continuous package rebuilds (if it's too tiring)

**Comment by Ste74** [comment]
Another think is use a release feature of github .. in the past we have used the github release ..

**Comment by Ste74** [comment]
Let me rebuild the manjaro-iso-profiles and pushing in all branch since now is broken ..
then @Kirek , @oberon2007 and @philmmanjaro what is your opinion here ?

**Comment by Chrysostomus** [comment]
My only problem with using the repo package is that it is hilariously out of date almost as a rule. I just wish for some kind of solution that keeps the installer working. 

Repo package has the advantage that it can be different for different branches. Git repo has the advantage of needing less maintenance.

**Comment by Chrysostomus** [comment]
For package method to work reliably, the package should be updated always when 

1) there is a change in any Packages-* file
2) when any package that is used by any iso profile is renamed or removed

Then it would work reliably
