### ISSUE TITLE
Add gnome-disk-utility in shared pkg list  

### ISSUE THREAD

**Issue by Ste74** [manjaro/iso-profiles#82]
Hi Team , related on [this](https://forum.manjaro.org/t/request-for-inclusion-of-gnome-disk-utility-package-in-live-media/28012) request in our forum , do you think if we install by default in any profiles ?

**Comment by Photon89** [comment]
I think, the topic starter wanted gnome-disk-utility to be available in the live environment only, not to have it amongst the packages being installed by the installer.

**Comment by Ste74** [comment]
Yep, sorry forgot to specify the "target" : packages-live

**Comment by lectrode** [comment]
Thanks for looking into this. If implemented, this will save a lot of time in future images.

I'm mainly requesting for the live-media. If I install manjaro on a machine I usually run a script to install a number of packages, including gnome-disk-utility, so I don't mind manually installing it after the installation. I could see the use in including it in the installation as well tho. I'll leave that up to you and the maintainers.

**Comment by Ste74** [comment]
After a little poll in the forum the winner is `gsmartcontrol` so we can include this and remove gnome-disk-utils where present ...

**Comment by lectrode** [comment]
Do we know if this is something that will be available in the next release?

**Comment by Ste74** [comment]
How about the use with wayland ? I.e. recently i notice that gparted not work in wayland , and is planned for gnome disk utility to add the similar function like gparted , so in a future prospective g-d-u seem the right choice ...

**Comment by lectrode** [comment]
I don't know. The point of the request wasn't to replace `gparted`. `gparted` provides a much-needed GUI partitioning tool and I use it frequently. The request is for a S.M.A.R.T. attribute viewer.

If g-d-u adds gparted functionality and support for wayland in the future, this can probably be reviewed at that time...but for now as long as we get either g-d-u or gsmartcontrol added to the live media, that would be ideal for the time being.

**Comment by philmmanjaro** [comment]
@Ste74: I've closed this one now. Open a [new issue](https://bugs.manjaro.org) if needed.
